### PR TITLE
Add init script & conf file

### PR DESCRIPTION
**Pull request by MrRoy**
This PR adds a openRC init script for libreddit, and also adds a configuration file in /etc/conf.d

### CODE REVIEW

**Comment by r7l** [comment]
Thanks allot for the PR. I will have to test it manually but it's pretty late already right now. 

By just looking over it, i am not entirely sure about the config file as i've never seen a conf.d file using `export`. Libreddit also comes with a hidden option called `LIBREDDIT_DEFAULT_SUBSCRIPTIONS`. It makes the entire thing work as if you have a Reddit start page. You can add a list of subs there and those will be shown if you load the front page. It might be worth to include this option (initially disabled) and maybe even add the [link](https://github.com/spikecodes/libreddit#change-default-settings) to docs as a comment on top. Even if the said option is missing.

**Comment by MrRoy** [comment]
Regarding the `export` point; the only way to pass configuration options to libreddit is through environment variables, it can't (AFAIK) be pointed to a configuration file
 With systemd, it's rather easy with a `EnvironmentFile=` parameter, but with OpenRC it's a bit more difficult.
Defining variables in a `conf.d` file passes them to the `init.d` file, but not to the daemon itself. The only way to pass them is by exporting them.
This works on my end at least, but if you know a better way to do this, I'm all ears.

As for `LIBREDDIT_DEFAULT_SUBSCRIPTIONS`, I wasn't aware of this. I'll add it to the config file and update the PR

**Comment by r7l** [comment]
Sorry for not being able to pass the PR. I was planning to look into a better way for the config file but haven't had time yet. I hope i'll find time soon.

**Comment by r7l** [comment]
@MrRoy I've actually found a better way for the config file. I've passed through the PR and changed the config in a separate commit. You might have to update your config on the next version. Thanks again for your contribution.

**Comment by MrRoy** [comment]
Thanks !

**Pull request merged**
